---
- hosts: multi
  gather_facts: no
  become: yes
  become_method: sudo
  serial: 1
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: k8s-rolling-update, tags: k8s-rolling-update }
