---
- hosts: multi
  gather_facts: yes
  become: yes
  roles:
    - { role: docker, tags: docker }


- hosts: masters
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/master, tags: master }
    - { role: cni, tags: cni }


- hosts: workers
  gather_facts: yes
  become: yes
  roles:
    - { role: kubernetes/node, tags: node }


- hosts: nfs
  gather_facts: yes
  become: yes
  roles:
    - { role: nfs-server, tags: nfs-server }
