---
- name: Add Kubernetes APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present


- name: Add Kubernetes APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    # 'focal' lsb is unavailable from repo
    # repo: deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-{{ ansible_lsb.codename }} main
    repo: deb [arch=amd64] http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: 'kubernetes'


# variables in dependencies in meta 'kubernetes/master' role
# dependencies:
#   - { role: commons/pre-install, packages: ["kubelet", "kubeadm", "kubectl"] }
- name: Install kubernetes packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}={{ package_version }}"
    update_cache: yes
    state: present
    force: True
  with_items: "{{ packages }}"


- name: Install utilities packages (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
    force: True
  with_items:
  - nfs-common


# kube-bench installer, apply to all nodes.
#- name: Upgrade kube-bench package if exists (Debian/Ubuntu)
#  when: ansible_os_family == "Debian"
#  apt:
#    deb: "{{ kubebench_url }}"
#  only_upgrade: True 
#  register: was_upgraded


#- name: Install kube-bench pacakge if not exists (Debian/Ubuntu)
#  when: ansible_os_family == "Debian"
#  apt:
#    deb: "{{ kubebench_url }}"
#  when: was_upgraded.false
