---
# tasks file for master
- name: Check if kubeadm has already run
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca


- name: Init cluster if needed
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes


# unused register 'started_kubelet'
- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet 


# pending task: install kubconfig in node
# sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
# sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: "Copy kubeconfig file to local laptop"
  fetch:
    src: /etc/kubernetes/admin.conf 
    dest: "{{ lookup('env', 'HOME') }}/admin.conf"
    flat: yes
  run_once: yes
  ignore_errors: yes
