---
# tasks file for docker
- name: Install Docker container engine
  include_tasks: packages.yaml


# https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/
# crictl by default connects on Unix to: unix:///run/containerd/containerd.sock or
# unix:///var/run/dockershim.sock or unix:///run/crio/crio.sock
- name: "Copy {{ crictl_config }} YAML files"
  template:
    src: "{{ item }}"
    dest: "{{ crictl_dir }}/{{ item | basename | regex_replace('\\.j2','') }}"
  with_fileglob:
    - ../templates/{{ crictl_config }}*.j2
