---
# https://sbulav.github.io/certifications/cks-gvisor/
# https://docs.docker.com/engine/install/ubuntu/
- name: Install required dpkg packages
  when: ansible_os_family == "Debian"
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - lsb-release
    state: present
    update_cache: yes


- name: Add Docker APT GPG key
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg


- name: Verify ansible_lsb
  debug: var=ansible_lsb.codename


- name: Add Docker APT repository
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }}  stable
    state: present
    filename: "docker"


- name: Install docker engine (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    update_cache: yes
    name: "docker.io={{ docker_version }}*"
    state: present


- name: Pin docker version
  when: ansible_os_family == "Debian"
  dpkg_selections:
    name: docker.io
    selection: hold
